slug: heretics-slog
created: 2026-02-17
obsidian: projects/heretics-slog/heretics-slog.md
github: https://github.com/sci-bok/heretics-slog
description: Heretic's Slog — science blog. Logic with passion.
